# Packer Image Backery
# azure-pipelines.yml

pool:
  vmImage: 'Ubuntu 18.04'
  
trigger:
- frontdoor

steps:

- task: PackerTool@0
  inputs:
    version: '1.5.5'

# Validate
- task: Packer@1
  displayName: 'ubuntu 18.04 packer validate'
  inputs:
    connectedServiceType: azure
    connectedServiceAzure: 'tf-infra-4711'
    templatePath: $(Pipeline.Workspace)/ubuntu1804.json
    #force: true|false Force a build to continue if artifacts exist, deletes existing artifacts
    #variables-file: JSON file containing user variables.
    #options: Additional options, see Packer Commands (CLI)  for more information.
    command: validate

# Build

- task: Packer@1
  displayName: 'ubuntu 18.04 packer build'
  inputs:
    connectedServiceType: azure
    connectedServiceAzure: 'tf-infra-4711'
    templatePath: $(Pipeline.Workspace)/ubuntu1804.json
    #force: true|false Force a build to continue if artifacts exist, deletes existing artifacts
    #variables-file: JSON file containing user variables.
    #options: Additional options, see Packer Commands (CLI)  for more information.
    command: build
